### ISSUE TITLE
request for addind liebearth devices driver

### ISSUE THREAD

**Issue by saidialhaye10** [actility/device-catalog#153]
### Request for Collaboration Access

Hello,

I am working on some improvements/features for this repository and would like to contribute directly. Could you please add me as a collaborator? My GitHub username is `saidialhaye10`.

Thank you!

**Comment by mostafaibr** [comment]
Hello @saidialhaye10 , 

Thank you in advance for your contribution. Can you please try to fork the repository, create a branch with your needed modifications, push it, and create a pull request? 

Here is a reference: https://gist.github.com/dlaehnemann/e6c8f46eee80112267af70ae92a3df13

**Comment by saidialhaye10** [comment]
thank you for the tips.
