### ISSUE TITLE
My manufacturer name is not in the list (lbearth)

### ISSUE THREAD

**Issue by saidialhaye10** [actility/device-catalog#162]
Hello,

I've created a driver (liebearth-generic-driver) which has been accepted, as I can see my driver in the list. However, I cannot add a device because my manufacturer name is not in the list.

Could you please assist with this issue?

**Comment by mostafaibr** [comment]
Hello, 

Do you mean on ThingPark Entreprise?

**Comment by saidialhaye10** [comment]
Yes please

**Comment by mostafaibr** [comment]
On ThingPark Entreprise, you don't need to create a driver. You would only add a device, and the driver on this repo will be used automatically.
However, your device is not yet available on ThingPark. 
As you can see here: https://github.com/actility/device-catalog/tags, the latest release of drivers and device profiles was done 3 weeks ago. Your device will be available after the next release planned for the ongoing week.

**Comment by saidialhaye10** [comment]
when adding a device i am asked to choose a manufacturer which should be mine (i can not find it in the list). 
My questioning is now  why do i find my driver in the driver list it the release is not done yet?
will my manufacturer name  be in the list after the release ?

thanks.

**Comment by tomHallActility** [comment]
Hello @saidialhaye10 

We just released our catalogs less than an hour ago. 
It might have taken a little more time to update on your side.
Can you please check again?

Thank you in advance,
Tom

**Comment by saidialhaye10** [comment]
Hello @tomHallActility  

I check and can now see my manufacturer name.

thank you for your help!
