### ISSUE TITLE
Availability of my driver on liveobject of orange

### ISSUE THREAD

**Issue by saidialhaye10** [actility/device-catalog#164]
Hello 

I would like to know if the driver i created (Liebearth-generic-driver)  is available on orange's live object.

if Not what should i do ?

thank you

**Comment by mostafaibr** [comment]
Hello, 

Unfortunately, the driver is not available directly on live object. 
However, we support receiving the flow of data from live object where the decoding/encoding process is supported then on our platform.

**Comment by saidialhaye10** [comment]
Hello 

Thank you for your answer.

Is there a way to make the driver available directly on live-object ? 

thank you

**Comment by mostafaibr** [comment]
Hello, 

Unfortunately, this is not available at the moment.

**Comment by saidialhaye10** [comment]
Thank you for your answer.
